-- MySQL Script generated by MySQL Workbench
-- Thu Mar 26 12:49:09 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`custinfo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`custinfo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`custinfo` (
  `id` INT NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `zipCode` VARCHAR(45) NOT NULL,
  `customer_pic` LONGBLOB NULL,
  PRIMARY KEY (`id`),
  INDEX `id` (`id` ASC) INVISIBLE,
  INDEX `Address` (`Address` ASC) INVISIBLE,
  INDEX `city` (`city` ASC) INVISIBLE,
  INDEX `state` (`state` ASC) INVISIBLE,
  INDEX `zipCode` (`zipCode` ASC) INVISIBLE,
  CONSTRAINT `login`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`login` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`itemInfo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`itemInfo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`itemInfo` (
  `indexNum` INT NOT NULL,
  `id` INT NOT NULL,
  `storeName` VARCHAR(45) NOT NULL,
  `itemLable` VARCHAR(45) NOT NULL,
  `itemLableTwo` VARCHAR(45) NULL,
  `price` DECIMAL(2) NOT NULL,
  `dateTime` DATETIME NOT NULL,
  `item_pic` LONGBLOB NULL,
  PRIMARY KEY (`indexNum`),
  INDEX `id_idx` (`id` ASC) VISIBLE,
  INDEX `id` (`id` ASC, `dateTime` ASC) INVISIBLE,
  CONSTRAINT `id`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`login` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`login`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`login` ;

CREATE TABLE IF NOT EXISTS `mydb`.`login` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `MI` VARCHAR(2) NULL,
  `suffix` VARCHAR(3) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`password`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`password` ;

CREATE TABLE IF NOT EXISTS `mydb`.`password` (
  `id` INT NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `idpass`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`login` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
